/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppCrmIndexRouteImport } from './routes/_app.crm.index'
import { Route as AppCrmTasksRouteImport } from './routes/_app.crm.tasks'
import { Route as AppCrmDealsRouteImport } from './routes/_app.crm.deals'
import { Route as AppCrmContactsRouteImport } from './routes/_app.crm.contacts'
import { Route as AppCrmBriefingRouteImport } from './routes/_app.crm.briefing'
import { Route as AppCrmTasksIndexRouteImport } from './routes/_app.crm.tasks.index'
import { Route as AppCrmDealsIndexRouteImport } from './routes/_app.crm.deals.index'
import { Route as AppCrmContactsIndexRouteImport } from './routes/_app.crm.contacts.index'
import { Route as AppCrmDealsDealIdRouteImport } from './routes/_app.crm.deals.$dealId'
import { Route as AppCrmContactsContactIdRouteImport } from './routes/_app.crm.contacts.$contactId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmTasksRoute = AppCrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmDealsRoute = AppCrmDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmContactsRoute = AppCrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmBriefingRoute = AppCrmBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmTasksIndexRoute = AppCrmTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmTasksRoute,
} as any)
const AppCrmDealsIndexRoute = AppCrmDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmDealsRoute,
} as any)
const AppCrmContactsIndexRoute = AppCrmContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmContactsRoute,
} as any)
const AppCrmDealsDealIdRoute = AppCrmDealsDealIdRouteImport.update({
  id: '/$dealId',
  path: '/$dealId',
  getParentRoute: () => AppCrmDealsRoute,
} as any)
const AppCrmContactsContactIdRoute = AppCrmContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => AppCrmContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/crm': typeof AppCrmRouteWithChildren
  '/crm/briefing': typeof AppCrmBriefingRoute
  '/crm/contacts': typeof AppCrmContactsRouteWithChildren
  '/crm/deals': typeof AppCrmDealsRouteWithChildren
  '/crm/tasks': typeof AppCrmTasksRouteWithChildren
  '/crm/': typeof AppCrmIndexRoute
  '/crm/contacts/$contactId': typeof AppCrmContactsContactIdRoute
  '/crm/deals/$dealId': typeof AppCrmDealsDealIdRoute
  '/crm/contacts/': typeof AppCrmContactsIndexRoute
  '/crm/deals/': typeof AppCrmDealsIndexRoute
  '/crm/tasks/': typeof AppCrmTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/crm/briefing': typeof AppCrmBriefingRoute
  '/crm': typeof AppCrmIndexRoute
  '/crm/contacts/$contactId': typeof AppCrmContactsContactIdRoute
  '/crm/deals/$dealId': typeof AppCrmDealsDealIdRoute
  '/crm/contacts': typeof AppCrmContactsIndexRoute
  '/crm/deals': typeof AppCrmDealsIndexRoute
  '/crm/tasks': typeof AppCrmTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/crm': typeof AppCrmRouteWithChildren
  '/_app/crm/briefing': typeof AppCrmBriefingRoute
  '/_app/crm/contacts': typeof AppCrmContactsRouteWithChildren
  '/_app/crm/deals': typeof AppCrmDealsRouteWithChildren
  '/_app/crm/tasks': typeof AppCrmTasksRouteWithChildren
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_app/crm/contacts/$contactId': typeof AppCrmContactsContactIdRoute
  '/_app/crm/deals/$dealId': typeof AppCrmDealsDealIdRoute
  '/_app/crm/contacts/': typeof AppCrmContactsIndexRoute
  '/_app/crm/deals/': typeof AppCrmDealsIndexRoute
  '/_app/crm/tasks/': typeof AppCrmTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/crm'
    | '/crm/briefing'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/tasks'
    | '/crm/'
    | '/crm/contacts/$contactId'
    | '/crm/deals/$dealId'
    | '/crm/contacts/'
    | '/crm/deals/'
    | '/crm/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/crm/briefing'
    | '/crm'
    | '/crm/contacts/$contactId'
    | '/crm/deals/$dealId'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/crm'
    | '/_app/crm/briefing'
    | '/_app/crm/contacts'
    | '/_app/crm/deals'
    | '/_app/crm/tasks'
    | '/_app/crm/'
    | '/_app/crm/contacts/$contactId'
    | '/_app/crm/deals/$dealId'
    | '/_app/crm/contacts/'
    | '/_app/crm/deals/'
    | '/_app/crm/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/tasks': {
      id: '/_app/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof AppCrmTasksRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/deals': {
      id: '/_app/crm/deals'
      path: '/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof AppCrmDealsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/contacts': {
      id: '/_app/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof AppCrmContactsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/briefing': {
      id: '/_app/crm/briefing'
      path: '/briefing'
      fullPath: '/crm/briefing'
      preLoaderRoute: typeof AppCrmBriefingRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/tasks/': {
      id: '/_app/crm/tasks/'
      path: '/'
      fullPath: '/crm/tasks/'
      preLoaderRoute: typeof AppCrmTasksIndexRouteImport
      parentRoute: typeof AppCrmTasksRoute
    }
    '/_app/crm/deals/': {
      id: '/_app/crm/deals/'
      path: '/'
      fullPath: '/crm/deals/'
      preLoaderRoute: typeof AppCrmDealsIndexRouteImport
      parentRoute: typeof AppCrmDealsRoute
    }
    '/_app/crm/contacts/': {
      id: '/_app/crm/contacts/'
      path: '/'
      fullPath: '/crm/contacts/'
      preLoaderRoute: typeof AppCrmContactsIndexRouteImport
      parentRoute: typeof AppCrmContactsRoute
    }
    '/_app/crm/deals/$dealId': {
      id: '/_app/crm/deals/$dealId'
      path: '/$dealId'
      fullPath: '/crm/deals/$dealId'
      preLoaderRoute: typeof AppCrmDealsDealIdRouteImport
      parentRoute: typeof AppCrmDealsRoute
    }
    '/_app/crm/contacts/$contactId': {
      id: '/_app/crm/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/crm/contacts/$contactId'
      preLoaderRoute: typeof AppCrmContactsContactIdRouteImport
      parentRoute: typeof AppCrmContactsRoute
    }
  }
}

interface AppCrmContactsRouteChildren {
  AppCrmContactsContactIdRoute: typeof AppCrmContactsContactIdRoute
  AppCrmContactsIndexRoute: typeof AppCrmContactsIndexRoute
}

const AppCrmContactsRouteChildren: AppCrmContactsRouteChildren = {
  AppCrmContactsContactIdRoute: AppCrmContactsContactIdRoute,
  AppCrmContactsIndexRoute: AppCrmContactsIndexRoute,
}

const AppCrmContactsRouteWithChildren = AppCrmContactsRoute._addFileChildren(
  AppCrmContactsRouteChildren,
)

interface AppCrmDealsRouteChildren {
  AppCrmDealsDealIdRoute: typeof AppCrmDealsDealIdRoute
  AppCrmDealsIndexRoute: typeof AppCrmDealsIndexRoute
}

const AppCrmDealsRouteChildren: AppCrmDealsRouteChildren = {
  AppCrmDealsDealIdRoute: AppCrmDealsDealIdRoute,
  AppCrmDealsIndexRoute: AppCrmDealsIndexRoute,
}

const AppCrmDealsRouteWithChildren = AppCrmDealsRoute._addFileChildren(
  AppCrmDealsRouteChildren,
)

interface AppCrmTasksRouteChildren {
  AppCrmTasksIndexRoute: typeof AppCrmTasksIndexRoute
}

const AppCrmTasksRouteChildren: AppCrmTasksRouteChildren = {
  AppCrmTasksIndexRoute: AppCrmTasksIndexRoute,
}

const AppCrmTasksRouteWithChildren = AppCrmTasksRoute._addFileChildren(
  AppCrmTasksRouteChildren,
)

interface AppCrmRouteChildren {
  AppCrmBriefingRoute: typeof AppCrmBriefingRoute
  AppCrmContactsRoute: typeof AppCrmContactsRouteWithChildren
  AppCrmDealsRoute: typeof AppCrmDealsRouteWithChildren
  AppCrmTasksRoute: typeof AppCrmTasksRouteWithChildren
  AppCrmIndexRoute: typeof AppCrmIndexRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmBriefingRoute: AppCrmBriefingRoute,
  AppCrmContactsRoute: AppCrmContactsRouteWithChildren,
  AppCrmDealsRoute: AppCrmDealsRouteWithChildren,
  AppCrmTasksRoute: AppCrmTasksRouteWithChildren,
  AppCrmIndexRoute: AppCrmIndexRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppRouteChildren {
  AppCrmRoute: typeof AppCrmRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCrmRoute: AppCrmRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
